# Generated by Django 5.1.6 on 2025-04-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_apiauth_id_alter_asset_id_alter_chain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='model_type',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('UTXO', 'UTXO')], db_index=True, default='ACCOUNT', help_text='区分链是 Account 模型还是 UTXO 模型', max_length=10, verbose_name='链模型类型'),
        ),
    ]
