###
POST http://localhost:8000/api/get_support_chain
Content-Type: application/json

{
    "chain": "bitcoin",
    "network": "mainnet"
}

###
POST http://localhost:8000/api/get_balance
Content-Type: application/json

{
    "device_id": "1111111221",
    "wallet_uuid": "222222111",
    "index":"0",
    "chain": "bitcoin",
    "symbol": "BTC",
    "network": "mainnet",
    "address": "36Sn1rywJ6V6xGU3BMZMsfg624jy4AXp3J",
    "contract_address": ""
}

###
POST http://localhost:8000/api/get_wallet_balance

{
    "device_id": "1111111221",
    "wallet_uuid": "222222111",
    "chain": "bitcoin"
}

### Note: get_nonce might return an error for UTXO chains like bitcoin
###
POST http://localhost:8000/api/get_nonce
Content-Type: application/json

{
    "chain": "bitcoin",
    "network": "mainnet",
    "symbol": "BTC",
    "address": "bc1qwvlvmha3cvhyq6qztjzumq2d63ffhtzyxxu6q8"
}

###
POST http://localhost:8000/api/get_account_info
Content-Type: application/json

{
    "chain": "bitcoin",
    "network": "mainnet",
    "symbol": "BTC",
    "address": "36Sn1rywJ6V6xGU3BMZMsfg624jy4AXp3J"
}

###
POST http://localhost:8000/api/get_fee
Content-Type: application/json

{
    "chain": "bitcoin",
    "network": "mainnet",
    "symbol": "BTC",
    "fee_way": "medium"
}

### 获取交易信息，包含nonce、gas等信息
POST http://localhost:8000/api/get_sign_tx_info
Content-Type: application/json

{
    "chain": "bitcoin",
    "network": "mainnet",
    "symbol": "BTC",
    "address": "bc1qwvlvmha3cvhyq6qztjzumq2d63ffhtzyxxu6q8"
}

###
POST http://localhost:8000/api/send_transaction
Content-Type: application/json

{
    "chain": "bitcoin",
    "network": "mainnet",
    "symbol": "BTC",
    "rawtx": "...raw_transaction_hex_string..."
}

###
POST http://localhost:8000/api/get_address_transaction
Content-Type: application/json

{
    "chain": "bitcoin",
    "network": "mainnet",
    "symbol": "BTC",
    "address": "bc1qwvlvmha3cvhyq6qztjzumq2d63ffhtzyxxu6q8",
    "contract_addr": "",
    "page": 1,
    "page_size": 20
}

###
POST http://localhost:8000/api/get_hash_transaction
Content-Type: application/json

{
    "chain": "bitcoin",
    "network": "mainnet",
    "symbol": "BTC",
    "hash": "7f12e9a5c7c44231376220d003ae94cc6c2ac9c7f6891cff6542ce28468b3c4f"
}

###
POST http://localhost:8000/api/get_unspend_list
Content-Type: application/json

# Note: This is only applicable for UTXO chains
{
    "chain": "bitcoin",
    "network": "mainnet",
    "address": "36Sn1rywJ6V6xGU3BMZMsfg624jy4AXp3J"
}

